[package]
name = "systest"
version = "0.1.0"
edition = "2018"
authors = ["Igor Gnatenko <ignatenko@redhat.com>"]
build = "build.rs"

[dependencies]
libsolv-sys = { path = "../libsolv-sys" }
libc = "0.2.48"

[build-dependencies]
ctest = "0.2.8"
cc = { version = "1.0.29", features = ["parallel"] }
